### ISSUE TITLE
Adelanto de gráfico con los modelos

### ISSUE THREAD

**Issue by Edirain6** [Edirain6/MasterTeam_Grupo3_G17#11]

**Comment by Edirain6** [comment]
![Image](https://user-images.githubusercontent.com/77688815/196415899-a8544854-337e-4d15-b448-3c47b19c3f37.png)

**Comment by Edirain6** [comment]
![Image](https://user-images.githubusercontent.com/77688815/196934762-c07228dc-c0a0-45b1-9f1a-6420196d602d.png)

**Comment by Edirain6** [comment]
![Image](https://user-images.githubusercontent.com/77688815/197308847-cf7e84cc-eee6-4769-ba8f-87ffb77fb828.png)

**Comment by Jencruzsa** [comment]
![Diagrama Entidad-Relación](https://user-images.githubusercontent.com/43911045/197368297-f33d4459-a048-494a-8e71-1df7dfff28df.jpg)
