### ISSUE TITLE
Sprint #1

### ISSUE THREAD

**Issue by Edirain6** [Edirain6/MasterTeam_Grupo3_G17#7]

**Comment by Edirain6** [comment]
Preparación y actualización del sprint #1

**Comment by Jencruzsa** [comment]
Se crea carpeta en el drive, se comparte con el grupo archivos que se estan trabajando

**Comment by Jencruzsa** [comment]
https://drive.google.com/drive/folders/1wPdQB3wTaqebGoeoFm9KEC6RjS954Lh4?usp=sharing

**Comment by Jencruzsa** [comment]
[Formato SPRINT#1.pdf](https://github.com/Edirain6/MasterTeam_Grupo3_G17/files/9845569/Formato.SPRINT.1.pdf)

**Comment by Jencruzsa** [comment]
[SPRINT#1.pdf](https://github.com/Edirain6/MasterTeam_Grupo3_G17/files/9848195/SPRINT.1.pdf)

**Comment by Jencruzsa** [comment]
[SPRINT#1.pdf](https://github.com/Edirain6/MasterTeam_Grupo3_G17/files/9852232/SPRINT.1.pdf)
